kite:
  keypair_name: "kitekey"
  public_key_path: "~/.ssh/kite.key.pub"
  private_key_path: "~/.ssh/kite.key"

aws:
  access_key: "enter your amazon key"
  secret_key: "enter your secret key"
  region: "eu-central-1"
  az: "eu-central-1a"
  vpc_cidr_block: "10.0.0.0/16"
  vpc_name: "platform-tools"
  platform_subnet_cidr_block: "10.0.0.0/24"
  platform_subnet_name: "platform_net"
  ops_subnet_cidr_block: "10.0.10.0/24"
  ops_subnet_name: "ops_services"

gcp:
  project: gcp-project
  region: europe-west1
  zone: europe-west1-b
  service_account: "~/safe/terraform.json"
  vpc_name: "platform-tools"
  subnet_name: "platform-net"
  subnet_cidr: "10.0.0.0/24"
  internal_gw: "10.0.0.1"

bosh:
  static_ip: "10.0.0.10"

concourse:
  hostname: "ci.domain.io"
  url: "http://ci.example.com"
  auth_username: "concourse"
  auth_password: "concourse"
  db_password: "changeme"
